[package]
name = "datacube"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cute = "0.3.0"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
rand = "0.8.5"
strum = "0.26.3"
strum_macros = "0.26.4"
